### ISSUE TITLE
jobs created by sync plugin do not show up in jenkins UI

### ISSUE THREAD

**Issue by bparees** [fabric8io/openshift-jenkins-sync-plugin#102]
The pipeline job exists on the filesystem, but it is not visible in the UI.

not sure if that means the job content on disk is corrupt or jenkins needs to be poked to refresh from disk or what, but the job configurations don't show up.

**Comment by gabemontero** [comment]
Turns out both myself and @csrwng have seen this, at least intermittently.  Today at least I saw it consistently until I changed https://github.com/jenkinsci/openshift-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/BuildConfigWatcher.java#L108 to 30 seconds.

Also, when tranversing Jenkins.isAcceptingTasks() in ecilpse, it took me to hudson.model.Node, where isAcceptingTasks() always returns true:  https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Node.java#L231-L233

I'm wondering if we need to switch to Computer.getCurrentComputer().isAcceptingTasks().

But we can go conservative and just bump the wait interval.  Per conversation with @bparees I'll tone down to 10 seconds in the PR I submit.

@jimmidyson FYI - thoughts?
